'use client';

import { useState } from 'react';
import { supabase } from '../lib/supabaseClient';

/**
 * AttendanceForm Component
 * Orchestrates service data entry, cloud synchronization, 
 * and automated executive reporting via WhatsApp.
 */
export default function AttendanceForm() {
  const [loading, setLoading] = useState(false);
  const [formData, setFormData] = useState({
    date: new Date().toISOString().split('T')[0],
    serviceType: 'Main Service',
    minister: '',
    topic: '',
    bibleText: '',
    men: 0,
    women: 0,
    children: 0,
    firstTimers: 0,
    converts: 0
  });

  /**
   * Generates a formatted executive summary and 
   * initiates a handover to the WhatsApp Web/App API.
   */
  const shareToWhatsApp = () => {
    const totalAttendance = (parseInt(formData.men) || 0) + (parseInt(formData.women) || 0) + (parseInt(formData.children) || 0);
    
    const message = `*CHURCH PULSE: MINISTRY IMPACT REPORT*%0A` +
      `*Service:* ${formData.serviceType}%0A` +
      `*Minister:* ${formData.minister || 'Not Specified'}%0A` +
      `*Topic:* ${formData.topic || 'N/A'}%0A%0A` +
      `*ATTENDANCE BREAKDOWN*%0A` +
      `• Men: ${formData.men}%0A` +
      `• Women: ${formData.women}%0A` +
      `• Kids: ${formData.children}%0A` +
      `*TOTAL:* ${totalAttendance}%0A%0A` +
      `*SOUL WINNING*%0A` +
      `• First Timers: ${formData.firstTimers}%0A` +
      `• New Converts: ${formData.converts} 🔥%0A%0A` +
      `_Generated by Rejoice Uzodinma Labs_`;
      
    window.open(`https://wa.me/?text=${message}`, '_blank');
  };

  /**
   * Validates state and persists data to the Supabase backend.
   * On success, triggers the optional reporting workflow.
   */
  const handleSave = async () => {
    if (!formData.minister || !formData.topic) {
        alert("Action Required: Please provide Minister and Sermon Topic.");
        return;
    }

    setLoading(true);
    try {
      const { error } = await supabase
        .from('church_reports') 
        .insert([{ 
          service_date: formData.date, 
          service_type: formData.serviceType,
          minister: formData.minister,
          topic: formData.topic,
          bible_text: formData.bibleText,
          men_count: parseInt(formData.men) || 0,
          women_count: parseInt(formData.women) || 0,
          children_count: parseInt(formData.children) || 0,
          first_timers: parseInt(formData.firstTimers) || 0,
          converts_count: parseInt(formData.converts) || 0
        }]);

      if (error) throw error;

      alert("Success: Record archived to cloud synchronization.");
      
      if(confirm("Deployment Successful! Generate WhatsApp Executive Summary?")) {
        shareToWhatsApp();
      }
    } catch (err) {
      alert(`System Error: ${err.message}`);
    } finally {
      setLoading(false);
    }
  };

  const inputStyle = "w-full bg-slate-50/80 border border-slate-200 p-4 rounded-2xl focus:ring-4 focus:ring-black/5 focus:border-black outline-none text-slate-900 transition-all font-medium placeholder:text-slate-400 shadow-sm";
  const labelStyle = "text-[10px] font-black text-slate-400 uppercase tracking-[0.2em] mb-2 block ml-1";

  return (
    <div className="min-h-screen bg-slate-50 py-12 px-4">
      <div className="max-w-xl mx-auto bg-white rounded-[3rem] shadow-[0_32px_64px_-16px_rgba(0,0,0,0.1)] overflow-hidden border border-slate-100">
        
        {/* Branding Header */}
        <div className="bg-black p-10 text-white text-left relative">
          <div className="absolute top-10 right-10 opacity-20 text-4xl font-black">RHM</div>
          <p className="text-[10px] font-black tracking-[0.3em] text-slate-400 mb-2">RCCG RHEMA ASSEMBLY PARISH</p>
          <h2 className="text-4xl font-black tracking-tighter uppercase">RhemaPulse</h2>
          <div className="mt-6 flex items-center gap-4">
             <a href="/dashboard" className="bg-white/10 hover:bg-white/20 px-4 py-2 rounded-full text-[10px] font-bold transition-all">
                ← ANALYTICS HUB
             </a>
          </div>
        </div>

        <div className="p-10 space-y-8">
          
          {/* Section 1: Logistics */}
          <section>
            <label className={labelStyle}>Administrative Logistics</label>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <input type="date" className={inputStyle} value={formData.date} onChange={(e) => setFormData({...formData, date: e.target.value})}/>
              <select className={inputStyle} value={formData.serviceType} onChange={(e) => setFormData({...formData, serviceType: e.target.value})}>
                <option>Main Service</option>
                <option>Workers Service</option>
                <option>Sunday School</option>
                <option>Tuesday Digging Deep</option>
                <option>Thursday Faith Clinic</option>
              </select>
            </div>
          </section>

          {/* Section 2: Spiritual Content */}
          <section className="space-y-4">
            <label className={labelStyle}>Sermon Content & Leadership</label>
            <input 
                placeholder="Minister in Charge" 
                className={inputStyle} 
                value={formData.minister}
                onChange={(e) => setFormData({...formData, minister: e.target.value})}
            />
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
               <input 
                placeholder="Sermon Topic" 
                className={inputStyle} 
                value={formData.topic}
                onChange={(e) => setFormData({...formData, topic: e.target.value})}
               />
               <input 
                placeholder="Bible Text (e.g. John 3:16)" 
                className={inputStyle} 
                value={formData.bibleText}
                onChange={(e) => setFormData({...formData, bibleText: e.target.value})}
               />
            </div>
          </section>

          {/* Section 3: Population Metrics */}
          <section>
            <label className={labelStyle}>Attendance Metrics</label>
            <div className="grid grid-cols-3 gap-4">
              {[
                { id: 'men', label: 'Men', icon: '👨' },
                { id: 'women', label: 'Women', icon: '👩' },
                { id: 'children', label: 'Kids', icon: '👶' }
              ].map((c) => (
                <div key={c.id} className="bg-slate-50/50 p-4 rounded-3xl border border-slate-100 text-center hover:border-slate-300 transition-all">
                  <span className="text-xl block mb-1">{c.icon}</span>
                  <span className="text-[9px] font-black text-slate-400 uppercase tracking-widest">{c.label}</span>
                  <input 
                    type="number" 
                    placeholder="0" 
                    value={formData[c.id] || ''}
                    className="w-full bg-transparent text-center text-2xl font-black outline-none text-black mt-1" 
                    onChange={(e) => setFormData({...formData, [c.id]: e.target.value})}
                  />
                </div>
              ))}
            </div>
          </section>

          {/* Section 4: Soul Winning */}
          <section>
            <label className={labelStyle}>Evangelism Impact</label>
            <div className="grid grid-cols-2 gap-4">
              <div className="bg-blue-50/30 p-4 rounded-3xl border border-blue-100 text-center">
                <span className="text-[9px] font-black text-blue-500 uppercase tracking-widest">First Timers</span>
                <input 
                    type="number" 
                    placeholder="0" 
                    value={formData.firstTimers || ''}
                    className="w-full bg-transparent text-center text-2xl font-black outline-none text-blue-600 mt-1" 
                    onChange={(e) => setFormData({...formData, firstTimers: e.target.value})}
                />
              </div>
              <div className="bg-emerald-50/30 p-4 rounded-3xl border border-emerald-100 text-center">
                <span className="text-[9px] font-black text-emerald-500 uppercase tracking-widest">New Converts</span>
                <input 
                    type="number" 
                    placeholder="0" 
                    value={formData.converts || ''}
                    className="w-full bg-transparent text-center text-2xl font-black outline-none text-emerald-600 mt-1" 
                    onChange={(e) => setFormData({...formData, converts: e.target.value})}
                />
              </div>
            </div>
          </section>

          {/* Primary Action Trigger */}
          <button onClick={handleSave} disabled={loading} 
            className="w-full p-6 bg-black text-white rounded-[2rem] font-black uppercase tracking-widest text-xs hover:bg-slate-800 transition-all shadow-[0_20px_40px_-10px_rgba(0,0,0,0.2)] active:scale-[0.98] disabled:opacity-50">
            {loading ? 'ARCHIVING TO CLOUD...' : 'DEPLOY REPORT'}
          </button>
          
          <footer className="text-center text-[10px] text-slate-400 font-medium">
            Engineered by Rejoice Uzodinma for RCCG Rhema Assembly © 2026
          </footer>
        </div>
      </div>
    </div>
  );
}